// discussions/forum page
export const LOAD_DISCUSSIONS_PAGE = 'LOAD_DISCUSSIONS_PAGE';
export const LOADED_DISCUSSIONS_PAGE = 'LOADED_DISCUSSIONS_PAGE';
export const FAIL_DISCUSSIONS_PAGE = 'FAIL_DISCUSSIONS_PAGE';
export const LOAD_DISCUSSION_PAGE = 'LOAD_DISCUSSION_PAGE';
export const LOADED_DISCUSSION_PAGE = 'LOADED_DISCUSSION_PAGE';
export const FAIL_DISCUSSION_PAGE = 'FAIL_DISCUSSION_PAGE';
export const NEW_DISCUSSION_ADDED = 'NEW_DISCUSSION_ADDED';
export const ADD_NEW_DISCUSSION = 'ADD_NEW_DISCUSSION';

export const INET_CONNECTED = 'INET_CONNECTED';
export const INET_DISCONNECTED = 'INET_DISCONNECTED';

export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

export const SAVE_UID = 'SAVE_UID';
export const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE';

export const REQ_NEWS_STORIES = 'REQ_NEWS_STORIES';
export const RECEIVED_NEWS_STORIES = 'RECEIVED_NEWS_STORIES';
export const LOADING_CACHE_NEWS_INTO_STORE = 'LOADING_CACHE_NEWS_INTO_STORE';
export const CACHE_EXPIRED_FETCHING_NEWS = 'CACHE_EXPIRED_FETCHING_NEWS';
export const SELECT_STORY = 'SELECT_STORY';

export const REQ_GIGS = 'REQ_GIGS';
export const RECEIVED_GIGS = 'RECEIVED_GIGS';
export const FILTERED_GIGS = 'FILTERED_GIGS';
export const LOADING_CACHE_GIGS_INTO_STORE = 'LOADING_CACHE_GIGS_INTO_STORE';
export const CACHE_EXPIRED_FETCHING_GIGS = 'CACHE_EXPIRED_FETCHING_GIGS';
export const SELECT_GIG = 'SELECT_GIG';
export const REMOVE_SELECT_GIG = 'REMOVE_SELECT_GIG';

export const REQ_ACTS = 'REQ_ACTS';
export const RECEIVED_ACTS = 'RECEIVED_ACTS';
export const SELECT_ACT = 'SELECT_ACT';
export const REMOVE_SELECT_ACT = 'REMOVE_SELECT_ACT';
export const CACHE_EXPIRED_FETCHING_ACTS = 'CACHE_EXPIRED_FETCHING_ACTS';
export const LOADING_CACHE_ACTS_INTO_STORE = 'LOADING_CACHE_ACTS_INTO_STORE';

// filters
export const FETCH_FILTERS = 'FETCH_FILTERS';
export const GIGS_FILTERED = 'GIGS_FILTERED';
export const LOAD_FILTERS = 'LOAD_FILTERS';
export const LOADED_FILTERS = 'LOADED_FILTERS';
export const FILTERS_CHANGED = 'FILTERS_CHANGED';
export const RESET_FILTERS = 'RESET_FILTERS';


